### ISSUE TITLE
Browser Example Please?

### ISSUE THREAD

**Issue by mattjohnsonpint** [bigeasy/timezone#138]
In the package description it says:

```
Timezone works in the browser too where it is less than 3K minified and gzipped.
```

Can you please provide an example of this?  At minimum please tell me which files I need to load so I can run it in the browser.  I assume the json tz data files need to go there as well - or are they compiled in somehow?  Looking at the build output, I'm really not sure all that is required.  Thanks.

**Comment by pushred** [comment]
If anyone's interested in doing this as a build step using browserify you can do so with a transform stream in [the deps phase][1] like so:

```js
var inlineTzData = through.obj(function (row, enc, next) {
  if (/timezone\/(?!index)/.test(row.file)) {
    var content = require(row.file);

    // Remove old TZ rules we don't need
    var year = new Date().getFullYear() - 1;
    for (var i in content) {
      for (var j in content[i]['rules']) {
        var rules = content[i]['rules'][j];
        for (var k = rules.length - 1; k >= 0; --k) {
          if (rules[k].to < year) {
            rules.splice(k, 1);
          }
        }
      }
    }

    row.source = 'module.exports = ' + JSON.stringify(content) + ';';
  }

  this.push(row);
  next();
});

browserify.pipeline.get('deps').push(inlineTzData);
```

Any timezone modules that have been required and are thus in browserify's dependency graph are loaded in the node process. Their output is JSON stringified and replaces the original file source. In our case we don't need any historical data so that's removed to keep filesize down.

[1]: https://github.com/substack/browserify-handbook#labeled-phases

**Comment by bcaller** [comment]
Just discovered some example code on the gh-pages branch. Check it out!
Also, see https://bigeasy.github.io/timezone/amd.html
